"""
label_checker.py (FULL UPDATED)

✅ Windows Tesseract path is hardcoded (as you confirmed):
    C:\Program Files\Tesseract-OCR\tesseract.exe

✅ What this file does (MVP for Rule 3(3) image label visibility):
1) Checks HTML/description labels in scraped_data["labels"]
2) Fetches the FIRST image URL from scraped_data["images"]
3) Runs OCR on the image and searches for AI/synthetic keywords
4) Computes label area ratio based ONLY on matched keyword word-boxes
5) Compliant if matched_area_ratio >= 10% (0.10)

Score (simple):
- 50 points: description label present
- 50 points: image label visible & >=10% area
"""

import io
import os
import re
import requests
import numpy as np
from PIL import Image

# ✅ OCR dependency
import pytesseract

# ✅ Your confirmed Windows path
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"


# ----------------------------
# Keywords
# ----------------------------

AI_KEYWORDS = [
    "ai-generated",
    "ai generated",
    "synthetic",
    "artificial",
    "deepfake",
    "computer generated",
    "generated by ai",
    "ai content",
]


def _build_keyword_tokens():
    tokens = set()
    for kw in AI_KEYWORDS:
        for tok in kw.replace("-", " ").split():
            tok = tok.strip().lower()
            if tok:
                tokens.add(tok)

    # extra variants often seen from OCR
    tokens.update(["aigenerated", "computergenerated"])
    return tokens


KEYWORD_TOKENS = _build_keyword_tokens()


# ----------------------------
# Helpers
# ----------------------------

def normalize_text(s: str) -> str:
    return (s or "").lower().replace("\n", " ").strip()


def contains_ai_keyword(text: str) -> bool:
    t = normalize_text(text)
    return any(kw in t for kw in AI_KEYWORDS)


def normalize_word_token(word: str) -> str:
    """
    Normalize OCR word for matching:
    - lower
    - remove non-alphanumeric characters
    """
    w = (word or "").strip().lower()
    w = re.sub(r"[^a-z0-9]+", "", w)
    return w


# ----------------------------
# MAIN API
# ----------------------------

def check_labels(scraped_data, url=None):
    """
    Check both:
    (A) Textual labels found in HTML (scraped_data["labels"])
    (B) Visible label on the FIRST image (scraped_data["images"][0])

    Returns:
    {
      desc_compliant, img_compliant,
      desc_labels, image_label_result,
      issues, score
    }
    """
    result = {
        "desc_compliant": False,
        "img_compliant": False,
        "desc_labels": [],
        "image_label_result": None,
        "issues": [],
        "score": 0,
        "source_url": url,
    }

    # --- (A) Description / HTML labels ---
    text_blob = ""
    for lbl in scraped_data.get("labels", []) or []:
        text_blob += (lbl.get("text") or "") + " "

    desc_text = normalize_text(text_blob)
    found_desc = [kw for kw in AI_KEYWORDS if kw in desc_text]

    if found_desc:
        result["desc_compliant"] = True
        result["desc_labels"] = found_desc

    # --- (B) Image label check (first image only) ---
    images = scraped_data.get("images", []) or []
    first_image = images[0] if images else None

    if first_image:
        try:
            img_check = check_image_label_from_url(first_image)
            result["image_label_result"] = img_check
            result["img_compliant"] = bool(img_check.get("compliant", False))
        except Exception as e:
            result["issues"].append("image_check_error: " + str(e))
    else:
        result["issues"].append("no_image_found")

    # --- Score (simple) ---
    score = 0
    score += 50 if result["desc_compliant"] else 0
    score += 50 if result["img_compliant"] else 0
    result["score"] = score

    if not result["desc_compliant"] and not result["img_compliant"]:
        result["issues"].append("no_ai_label_detected_in_desc_or_image")

    return result


# ----------------------------
# IMAGE CHECKER (OCR + AREA)
# ----------------------------

def check_image_label_from_url(image_url, timeout=15):
    """
    Fetch image -> OCR -> detect keyword -> compute matched keyword word boxes area ratio.

    Returns:
    {
      image_url,
      fetched,
      size_bytes,
      width,height,
      ocr_text,
      matched_words: [{word, box:[x,y,w,h]}],
      matched_area_ratio,
      compliant,
      notes:[...]
    }
    """
    result = {
        "image_url": image_url,
        "fetched": False,
        "size_bytes": None,
        "width": None,
        "height": None,
        "ocr_text": None,
        "matched_words": [],
        "matched_area_ratio": 0.0,
        "compliant": False,
        "notes": [],
    }

    # 1) Fetch image
    headers = {"User-Agent": "Mozilla/5.0"}
    resp = requests.get(image_url, timeout=timeout, headers=headers)
    resp.raise_for_status()

    content = resp.content
    result["fetched"] = True
    result["size_bytes"] = len(content)

    # 2) Decode with PIL
    img = Image.open(io.BytesIO(content)).convert("RGB")
    w, h = img.size
    result["width"] = w
    result["height"] = h

    if not w or not h:
        result["notes"].append("invalid_image_dimensions")
        return result

    image_area = float(w * h)

    # 3) OCR with word boxes
    try:
        arr = np.array(img)

        # grayscale for OCR
        gray = (0.299 * arr[:, :, 0] + 0.587 * arr[:, :, 1] + 0.114 * arr[:, :, 2]).astype(np.uint8)

        data = pytesseract.image_to_data(gray, output_type=pytesseract.Output.DICT)

        words = data.get("text", []) or []
        full_text = " ".join([t for t in words if t and t.strip()])
        result["ocr_text"] = full_text.strip()

        # Fast fail: keyword phrase not present at all
        if not contains_ai_keyword(full_text):
            result["compliant"] = False
            result["notes"].append("no_ai_keywords_in_ocr_text")
            return result

        # 4) Sum ONLY matched keyword word boxes
        matched_area = 0.0
        matched_words = []

        n = len(words)
        for i in range(n):
            word_raw = (words[i] or "").strip()
            if not word_raw:
                continue

            tok = normalize_word_token(word_raw)
            if not tok:
                continue

            if tok in KEYWORD_TOKENS:
                left = int(data["left"][i])
                top = int(data["top"][i])
                bw = int(data["width"][i])
                bh = int(data["height"][i])

                box_area = float(max(bw, 0) * max(bh, 0))
                matched_area += box_area
                matched_words.append({"word": word_raw, "box": [left, top, bw, bh]})

        ratio = matched_area / image_area if image_area > 0 else 0.0

        result["matched_words"] = matched_words
        result["matched_area_ratio"] = ratio

        # ✅ Rule 3(3) MVP: label >=10% surface area
        result["compliant"] = ratio >= 0.10

        if result["compliant"]:
            result["notes"].append("label_area_meets_10_percent")
        else:
            result["notes"].append("label_detected_but_area_below_10_percent")

        if not matched_words:
            result["notes"].append("keyword_phrase_found_but_token_boxes_not_matched")

        return result

    except Exception as e:
        result["notes"].append(f"ocr_error: {e}")
        result["compliant"] = False
        return result


# ----------------------------
# OPTIONAL STUBS
# ----------------------------

def detect_labels_in_screenshot(screenshot_path):
    """
    Optional stub: if later you take screenshots of pages instead of direct image URLs.
    """
    return {
        "stub": True,
        "message": "Screenshot analysis not yet implemented (use OpenCV + pytesseract).",
        "screenshot_path": screenshot_path,
    }


def verify_label_visibility(label_data):
    """
    Optional stub: deeper checks (font size, contrast ratio, placement).
    MVP currently checks only keyword label presence + >=10% area heuristic.
    """
    requirements = {
        "min_font_size_pt": 12,
        "min_contrast_ratio": 4.5,
        "acceptable_positions": ["top", "bottom", "overlay"],
    }

    return {
        "meets_requirements": False,
        "requirements": requirements,
        "message": "Not implemented. MVP only checks keyword label presence + >=10% area heuristic.",
    }
